---
title: "Group_2_Work"
author: "Alex H & Elvis"
date: "2023-06-21"
output: pdf_document
---
```{r setup, include=FALSE}
library(here)
library(ggplot2)
library(scales)
library(tidyverse)
library(modelr)

theme_set(theme_bw())
options(repr.plot.width=4, repr.plot.height=3)
knitr::opts_chunk$set(echo = TRUE)
```
## Load Data
```{r load-data}
city_day_agg_cleaned <- read_csv(gzfile('city_day_agg_cleaned.csv.gz'))
country_day_agg_cleaned <- read_csv(gzfile('country_day_agg_cleaned.csv.gz'))
openaq_cities <- read_csv('openaq_cities.csv')
```

## Density
```{r density}
#divide city dataframe into two, 2017-2019 and 2020 so you can get the averages for each month and compare them to get the change in the chemical      

before_2020 <- city_day_agg_cleaned %>%
  filter(year(date) < 2020 & month(date) < 6)

after_2020 <- city_day_agg_cleaned %>%
  filter(year(date) >= 2020 & month(date) < 6)

before_2020 <- before_2020 %>%
  group_by(countryCode, city_id, parameter) %>%
  summarize(agg_mean = mean(mean)) %>%
  mutate(before_2020 = TRUE) %>% 
  ungroup %>% 
  group_by(parameter) %>% 
  mutate(med = median(agg_mean))

after_2020 <- after_2020 %>%
  group_by(countryCode, city_id, parameter) %>%
  summarize(agg_mean = mean(mean)) %>%
  mutate(before_2020 = FALSE) %>% 
  ungroup %>% 
  group_by(parameter) %>% 
  mutate(med = median(agg_mean))

df <- bind_rows(before_2020, after_2020)

ggplot(df, aes(x = agg_mean, fill = before_2020)) +
  geom_density(alpha = 0.5) +
  geom_vline(data = subset(df, !before_2020), aes(xintercept = med), color = "red", size = 1) +
  geom_vline(data = subset(df, before_2020), aes(xintercept = med), color = "blue", size = 1) +
  labs(
    title = "Distribution of Air Pollution",
    x = "Parameter",
    y = "Density"
  ) +
  facet_wrap(~ parameter, scales = "free") +
  scale_fill_manual(values = c("red", "blue"),
                    labels = c("2020", "3-yr avg"),
                    guide = guide_legend(title = "Period"))
```

## Aggregate Mean Map
```{r map}
# Get the world map data
world_map <- map_data("world")

# Join the data frames
df <- left_join(df, openaq_cities, by = c("countryCode", "city_id"))

# Plot the world map with agg_mean points
ggplot() +
  geom_polygon(data = world_map,
               aes(x = long, y = lat, group = group),
               fill = "lightgray", color = "white") +
  geom_point(data = df,
             aes(x = Lon, y = Lat, color = agg_mean),
             size = 0.1, alpha = 0.7) +
  scale_color_gradient(low = "purple", high = "orange") +
  labs(title = "Air Pollution by City",
       x = "Longitude",
       y = "Latitude",
       color = "Agg Mean") +
  facet_wrap(~ parameter, scales = "free")
```

## Relative Change Map
```{r rel-change}
col_to_remove <- c('med')

df_rel_change <- df %>% select(- one_of(col_to_remove)) %>%  pivot_wider(names_from = before_2020, values_from = agg_mean) %>% na.omit()

#These two lines change the column name from TRUE and FALSE so we can actually use them in a mutate
colnames(df_rel_change)[6] = "before_2020"

colnames(df_rel_change)[7] = "after_2020"

df_rel_change <- df_rel_change %>% mutate(percent_change = (((before_2020 - after_2020)/before_2020))*100)

# Plot the world map with percent_change points
ggplot() +
  geom_polygon(data = world_map,
               aes(x = long, y = lat, group = group),
               fill = "lightgray", color = "white") +
  geom_point(data = df_rel_change,
             aes(x = Lon, y = Lat, color = percent_change),
             size = 0.1, alpha = 0.7) +
  scale_color_gradient(low = "purple", high = "orange") +
  labs(title = "Air Pollution by City",
       x = "Longitude",
       y = "Latitude",
       color = "Percent Change") +
  facet_wrap(~ parameter, scales = "free")
```

## Relative Change by Country
```{r rel-change-by-country}
# Filter the data for each parameter category and calculate mean and standard error
df_rel_change_by_country <- df_rel_change %>%
  group_by(countryCode, parameter) %>% 
  summarize(mean_change = mean(percent_change),
            se = sd(percent_change) / sqrt(n()))

df_no2 <- df_rel_change_by_country[df_rel_change_by_country$parameter == "no2", ]
df_o3 <- df_rel_change_by_country[df_rel_change_by_country$parameter == "o3", ]
df_pm25 <- df_rel_change_by_country[df_rel_change_by_country$parameter == "pm25", ]

# Plot for no2 with standard error bars
ggplot(data = df_no2, aes(y = countryCode, x = mean_change)) +
  geom_point() +
  geom_errorbarh(aes(xmin = mean_change - se, xmax = mean_change + se), height = 0.2) +
  labs(title = "Air Pollution by Country - no2",
       y = "Country",
       x = "Percent Change")

# Plot for o3 with standard error bars
ggplot(data = df_o3, aes(y = countryCode, x = mean_change)) +
  geom_point() +
  geom_errorbarh(aes(xmin = mean_change - se, xmax = mean_change + se), height = 0.2) +
  labs(title = "Air Pollution by Country - o3",
       y = "Country",
       x = "Percent Change")

# Plot for pm25 with standard error bars
ggplot(data = df_pm25, aes(y = countryCode, x = mean_change)) +
  geom_point() +
  geom_errorbarh(aes(xmin = mean_change - se, xmax = mean_change + se), height = 0.2) +
  labs(title = "Air Pollution by Country - pm25",
       y = "Country",
       x = "Percent Change")


```